CREATE DATABASE tracker;
CREATE USER athelte@localhost IDENTIFIED BY 'cpsc';
GRANT ALL privileges ON tracker .* TO athlete@localhost;
USE tracker;
CREATE TABLE USER(ID INT NOT NULL, Date_of_birth DATE, Sex VARCHAR(6), First_name VARCHAR(20), Last_name VARCHAR(20), Weight INT NOT NULL, Height INT, Password VARCHAR(20), Profile_type VARCHAR(10), PRIMARY KEY(ID));

CREATE TABLE ATHLETE(Athlete_ID INT NOT NULL,PRIMARY KEY(Athlete_ID),FOREIGN KEY(Athlete_ID) REFERENCES USER(ID));

CREATE TABLE COACH(Coach_ID INT NOT NULL,PRIMARY KEY(Coach_ID),FOREIGN KEY(Coach_ID) REFERENCES USER(ID));

CREATE TABLE ACCESSES_INFORMATION(Athlete_ID INT NOT NULL,Coach_ID INT NOT NULL, PRIMARY KEY(Athlete_ID,Coach_ID), FOREIGN KEY(Athlete_ID) REFERENCES ATHLETE(Athlete_ID),FOREIGN KEY(Coach_ID) REFERENCES COACH(Coach_ID));

CREATE TABLE DAY(Date DATE NOT NULL, Day_Owner_ID INT NOT NULL, Weight INT, PRIMARY KEY(Date,Day_Owner_ID),FOREIGN KEY(Day_Owner_ID) REFERENCES USER(ID));

CREATE TABLE EXERCISE(Name VARCHAR(20) NOT NULL, User_ID INT NOT NULL, PRIMARY KEY(Name,User_ID), FOREIGN KEY(User_ID) REFERENCES USER(ID));

CREATE TABLE PERFORMANCE_METRIC(Metric_name VARCHAR(20) NOT NULL, Owner_ID INT NOT NULL, Units VARCHAR(20), PRIMARY KEY(Metric_name,Owner_ID),FOREIGN KEY(OWNER_ID) REFERENCES USER(ID));

CREATE TABLE METRIC_DESCRIBES_EXERCISE(Metric_name VARCHAR(20) NOT NULL, Metric_user_ID INT NOT NULL, Exercise_name VARCHAR(20) NOT NULL, PRIMARY KEY(Metric_name,Metric_user_ID,Exercise_name),FOREIGN KEY(Metric_name) REFERENCES PERFORMANCE_METRIC(Metric_name),FOREIGN KEY(Metric_User_ID) REFERENCES PERFORMANCE_METRIC(Owner_ID),FOREIGN KEY(Exercise_name) REFERENCES EXERCISE(Name));

CREATE TABLE WORKOUT(Workout_ID INT NOT NULL, User_ID INT NOT NULL, Day DATE NOT NULL, PRIMARY KEY(Workout_ID),FOREIGN KEY(User_ID) REFERENCES USER(ID), FOREIGN KEY(Day) REFERENCES DAY(Date));

Drop table exercise_submission;
CREATE TABLE EXERCISE_SUBMISSION(Submission_ID INT NOT NULL, Exercise_name VARCHAR(20) NOT NULL, User_ID INT NOT NULL, Workout_ID INT NOT NULL, PRIMARY KEY(Submission_ID));

Drop table metric_measures_submission;
CREATE TABLE METRIC_MEASURES_SUBMISSION(Metric_name VARCHAR(20) NOT NULL, Metric_owner_ID INT NOT NULL, Submission_ID INT NOT NULL, Metric_Value FLOAT(24),PRIMARY KEY(Metric_name,Metric_owner_ID,Submission_ID));


CREATE TABLE FOOD(Name VARCHAR(20) NOT NULL, User_ID INT NOT NULL, Milliters_Per_Serving INT NOT NULL, Grams_Per_Servings INT NOT NULL, Fats INT NOT NULL, Carbs INT NOT NULL, Protein INT NOT NULL, Calories INT NOT NULL, PRIMARY KEY(Name,User_ID),FOREIGN KEY(User_ID) REFERENCES USER(ID));


CREATE TABLE MEAL(Meal_ID INT NOT NULL,User_ID INT NOT NULL, Day DATE NOT NULL, PRIMARY KEY(Meal_ID), FOREIGN KEY(User_ID) REFERENCES USER(ID));
alter table food rename column grams_per_servings to grams_per_serving;

drop table food_is_part_of_meal;
CREATE TABLE FOOD_IS_PART_OF_MEAL(Food_name VARCHAR(20), User_Food_ID INT NOT NULL, Meal_ID INT NOT NULL, SERVINGS FLOAT(24), PRIMARY KEY(Food_name,User_Food_ID,Meal_ID) );
